version: '3.8'

services:
  task_management_microservice:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - task_management_network
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_management_network


networks:
  task_management_network:

volumes:
  postgres_data: